# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1792b29b0fc89be097a82485eae25ab939b902cee3b7bd0b74e7693b17399769bab2374aee7eddc61814fe3fbdc47717308d882f8555fc9161c50f076748645

test:
  secret_key_base: 7ba01a3ddcc44dd7c905f04bc46abbc46b0702c75bb651ad560d50bd32c79355f4f279b6298eca66fb3337a64ccda81eceaa510fd454b5d18de694b1f6c6e106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
